ISQ.Cnf_Float = {
serverUrl : "my.nanorep.com", 
limited : false,
translationLanguages : "",
translationDetectionOnly : false,
kbLanguageCode : "iw",
customEscalationLink : "",
customEscalationLink_target : 1,
useCustomEncoding : false,
customEncoding : "windows-1255",
translationEnabled : false,
translationApiKey : "Microsoft:\'9F604984C15229D2ED188B3B0F900D5F87581FB1\',GoogleV1:\'AIzaSyB4Ecx3LpOKRXB8aYeuoWTLGI_EVLZ98uw\',GoogleV2:\'AIzaSyCADmMZJx-J7cDiXDniXmNIo6oaeaqpve8\'",
chatEnabled : false,
livePersonID : "",
showChatConfiguration : 0,
alwaysShowEscalationLink : false,
customEscalationLink_Action : 1,
floatSideMargin : 10,
floatBottomMargin : 10,
floatWidgetContainerPadding : "0",
floatTeaser_ContainerSize : [186,57],
floatTeaser_WidgetSize : [186,57],
floatTeaser_WidgetPosition : [0,0],
floatCollapsed_ContainerSize : [338,57],
floatCollapsed_WidgetSize : [338,57],
floatCollapsed_WidgetPosition : [0,0],
floatExpanded_ContainerSize : [338,354],
floatExpanded_WidgetSize : [338,354],
floatExpanded_WidgetPosition : [0,0],
floatChat_ContainerSize : [338,400],
floatChat_WidgetSize : [338,400],
floatChat_WidgetPosition : [0,0],
floatTeaserImage : "",
floatCollapsedImage : "",
floatExpandedImage : "",
floatChatImage : "",
floatContainerBoxShadow : "rgba(170, 170, 170, 0.6) 3px 3px 3px",
floatOpenOnHover : true,
floatTeaserShowsWidget : true,
floatTeaser_text : "",
floatTeaser_textColor : "Black",
floatTeaser_textFont : "font-family:Arial;font-size:14px;font-weight:bold;text-decoration:none;font-style:normal",
floatTeaser_textPosition : [17,6],
floatTeaser_textSize : [85,30],
floatLoadSize : [186,0],
titleNormalText : "שאל שאלה וקבל תשובה ממאגר התשובות:",
titleTeaserText : "יש לך שאלה?",
customChatButtonText : "",
customEmailButtonText : "דוא\"ל",
customAskRepByText : "שאל נציג ב:",
customNoAnswersText : "נא מקד שאלתך</p><p dir=\"RTL\">למידע נוסף נא פנה למוקד שירות הלקוחות בטלפון:</p><p dir=\"RTL\">03-5194111&nbsp;שלוחה 12</p>",
dockRTL : true,
answerFooter : "",
showFooterOnlyOnLastAnswer : false,
initialText : "הקלד את שאלתך כאן",
titleColor : "White",
floatOpenOnHover : true,
floatOpenOnLoad : false,
floatAutoMinimizeTimeout : "0",
autoQuestions : "",
autoQuestionsInterval : "5000",
autoQuestionsTypeEffect : true,
repeatAutoQuestions : true,
generatedTeaser_textFont : "font-family:Arial;font-size:16px;font-weight:bold;text-decoration:none;font-style:normal",
generatedTeaser_textPosition : [15,3],
generatedTeaser_textSize : [160,40],
floatMarginBottom : 6,
floatCollapsed_WidgetSize : [338,57],
floatTeaser_WidgetSize : [186,57],
customerBrandingText : "",
showLogoInCollapsedMode : true,
showFooterWithContactForm : true,
customCSS : "\t div#widgetTitleText {\t font-family: Arial;\t font-size: 16px;\t font-weight:bold;\t text-decoration:none;\t font-style:normal;\t color: White;}\t div#widgetTitleWrapper {\t background-color: #332773;}\t div#widgetFooterWrapper {\t background-color: #332773;}\t div#widgetMinimizedFooter {\t background-color: #332773;}\t td.answerTitle {\t font-family: Arial;\t font-size: 12px;\t font-weight:bold;\t text-decoration:none;\t font-style:normal;\t color: #00005A;}\t td.answerBody {\t font-family: Arial;\t font-size: 12px;\t font-weight:normal;\t text-decoration:none;\t font-style:normal;\t color: #333333;}\t .answerTable TD A, .answerBackLinkContainer A {\t color: #332773;}\t #customerBrandingText {\t font-family: Arial;\t font-size: 12px;\t font-weight:bold;\t text-decoration:none;\t font-style:normal;}",
skinCSS : "/* widget title */\r\n#widgetTitleWrapper {\r\n    background-color:#e9682d;\r\n\t-moz-border-radius: 5px 5px 0 0;\r\n\t-webkit-border-radius: 5px 5px 0 0;\r\n\tborder-radius: 5px 5px 0 0;\r\n}\r\n#widgetTitleText {\r\n    color:#FFF;      \r\n}\r\n\r\n/* search box */\r\n#searchContainerWrapper {\r\n    background-color: #ededed;    \r\n}\r\n#searchContainer {\r\n    border:1px solid #dddddd;\r\n}\r\n#txtSearch {\r\n    color:#666;\r\n}\r\n\r\n/* content area */\r\n#contentAreaWrapper {\r\n    color: #5F6061;\r\n    border-right: 1px solid #F0F0F0;\r\n    border-left: 1px solid #F0F0F0;\r\n}\r\n\r\n/* results hint */\r\n#resultsHint {\r\n    color:#b5b5b5;\r\n}\r\n\r\n/* answers */\r\n.answerTitle {\r\n    color:#00005a;    \r\n}\r\n\r\n\r\n/* action bar */\r\n#actionBarWrapper {\r\n    color:#5F6061;\r\n    background-color: #F0F0F0;\r\n}\r\n\r\n.actionBar A,\r\n.actionBar A:visited {\r\n    color:#727070;\r\n}\r\n\r\n/* widget footer */\r\n#widgetFooterWrapper {\r\n    color:#FFF;    \r\n    background-color:#e9682d;\r\n\t-moz-border-radius: 0 0 3px 3px;\r\n\t-webkit-border-radius: 0 0 3px 3px;\r\n\tborder-radius: 0 0 3px 3px;\r\n}\r\n#widgetMinimizedFooter {\r\n    background-color:#e9682d;\r\n\t-moz-border-radius: 0 0 3px 3px;\r\n\t-webkit-border-radius: 0 0 3px 3px;\r\n\tborder-radius: 0 0 3px 3px;\r\n}\r\n\r\n#widgetFooter A,\r\n#widgetFooter A:visited,\r\n#widgetFooter A .link_nano,\r\n#widgetFooter A .link_rep\r\n{\r\n    color:#FFF;\r\n}\r\n\r\n/* chat */\r\n#chatStatusContainer {\r\n    color:#5F6061;\r\n    background-color: #F0F0F0;\r\n}\r\n#closeChat {\r\n    color:#5F6061;\r\n}\r\n#chatInputWrapper {\r\n    background-color: #F0F0F0;\r\n}\n#chatInputContainer {\n    border:solid 1px #D8D6D6;\n\tborder-radius:5px;\r\n\t-moz-border-radius: 5px;\n}\n#txtEmailChat {\r\n    color:#666;\r\n    border: 1px solid #D8D6D6;\r\n}\r\n\n\n/* chat suggestions */\n#chatSuggestions {\r\n    border:1px solid #D8D6D6;\r\n    background:#fff;\r\n}\n.chatSuggestionHover {\n    background: #DCE6F4;\n}\r\n\r\n/* chat quick answers */\r\n.quickAnswer {\n    color:#2D3F87;\n}\r\n.quickAnswerBody {\r\n    border-left-color:#2D3F87;\r\n}\r\n\r\n/* translation tooltip */\n.translationTooltip {\n    border:solid 1px #c0c0c0;\n    background-color: #f3f4f8;\n}\n\n/* logo in collapsed mode */\r\n#logoInCollapsedMode\r\n{\r\n\tposition:absolute;\r\n\ttop:29px;\r\n\tright:10px;\r\n\tleft: auto;\r\n}\r\n#logoInCollapsedMode A\r\n{\r\n\tfont-weight:normal;\r\n\tfont-size:16px;\r\n\ttext-decoration:none;\r\n\tfont-family:Times New Roman;\r\n}\r\n",
skinCSS_rtl : "html.rtl_css_file {direction:rtl;/*keep this */}\r\n\r\n#widgetTitleText {\r\n\tpadding: 0px 10px 0 0;\r\n}\r\n\r\n#logoInCollapsedMode\r\n{\r\n\tleft:10px;\r\n\tright:auto;\r\n}" 
}
