
import CDate.CDate;
import DBCONNECT.TRS;
import Utils.MySimleInputByCombo;
import java.sql.Connection;

/*
 * addDeal.java
 *
 * Created on 1 דצמבר 2008, 17:37
 */



/**
 *
 * @author  Dmitry
 */
public class addDeal extends javax.swing.JFrame {
int dealid=0;
String din="none";
boolean completelynew=false;
int folderid=0;
    /** Creates new form addDeal */
    public addDeal(int dealid,String din) {
        initComponents();
        
        this.dealid=dealid;
        this.din=din;
        this.dealidname.setText(din);
         this.menayaselect.setEnabled(completelynew);
         setVisible(true);
    }
     public addDeal(int dealid,int folderid,boolean completelynew) {
        initComponents();
        this.completelynew=completelynew;
        this.dealid=dealid;
        this.din="";
        this.folderid=folderid;
        this.dealidname.setText(din);
        this.menayaselect.setEnabled(completelynew);
         setVisible(true);
    }

    private void adddeal(int tdealid, CDate d, int iopid, int ifid, float fqtty, float fprice, float fpriceorig) {
        Connection con=BursaAnalizer_Frame.getConnectToDB(BursaAnalizer_Frame.DBID_USER).con;
       TRS rs=new TRS(con);
       String sql="";
         sql="INSERT INTO OPERATIONS " +
        "(DEALID,DATE,OP_TYPE,FORMULAID,QTTY,PRICE,orig,CURENTSIKUN,FIRSTSIKUN) " +
        "VALUES("+tdealid+",'"+
        d.getMonth()+"/"+d.getDay()+"/"+d.getYear()+"',"+
        iopid+","+
        ifid+","+
        fqtty+","+
        fprice+","+
        fpriceorig+",0.0,0.0)";
        rs.execSQL(sql);
    }

    private int addnewdealtodeal(int folderid, int mid) {
        Connection con=BursaAnalizer_Frame.getConnectToDB(BursaAnalizer_Frame.DBID_USER).con;
       TRS rs=new TRS(con);
       String sql="";
         sql="INSERT INTO DEAL " +
        " (FOLDERID,MENAYAID) " +
        "VALUES("+folderid+","+mid+")";
         rs.execSQL(sql);
         sql="SELECT DEALID FROM DEAL " +
        " WHERE FOLDERID="+folderid+" AND MENAYAID="+mid; 
         return rs.rowExistID(sql,"DEALID");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        close = new javax.swing.JButton();
        ok = new javax.swing.JButton();
        price = new javax.swing.JTextField();
        qtty = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        dateButton = new CalendarForms.DateButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dealidname = new javax.swing.JLabel();
        menayaselect = new javax.swing.JComboBox();
        optype = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        fidn = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        price1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        ok.setText("ok");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        price.setText("0.0");
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });

        qtty.setText("0.0");

        jLabel1.setText("price");

        jLabel2.setText("qtty");

        jLabel3.setText("Date");

        jLabel5.setText("Menaya");

        dealidname.setText("none");

        menayaselect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Connection con4=BursaAnalizer_Frame.getConnectToDB(BursaAnalizer_Frame.DBID_BASE).con;
        MySimleInputByCombo cbind4 = new MySimleInputByCombo (null, con4, "[MENAYA_BASE]", "NAME", "MENAYA_ID");
        menayaselect=cbind4;

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(35, 35, 35)
                        .addComponent(dealidname))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(menayaselect, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dealidname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menayaselect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        optype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Connection con2=BursaAnalizer_Frame.getConnectToDB(BursaAnalizer_Frame.DBID_BASE).con;
        MySimleInputByCombo cbind2 = new MySimleInputByCombo (null, con2, "[OPTYPES_T]", "VAL", "OP_TYPE_ID");
        optype=cbind2;

        jLabel4.setText("Type");

        fidn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Connection con3=BursaAnalizer_Frame.getConnectToDB(BursaAnalizer_Frame.DBID_BASE).con;
        MySimleInputByCombo cbind3 = new MySimleInputByCombo (null, con3, "[FORMULA_T]", "NAME", "FORMULAID");
        fidn=cbind3;

        jLabel6.setText("Formula");

        price1.setText("0.0");
        price1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Original");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(price, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qtty, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                                .addGap(49, 49, 49)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(price1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ok)
                                        .addGap(36, 36, 36)
                                        .addComponent(close))
                                    .addComponent(optype, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fidn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(qtty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fidn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(close)
                    .addComponent(ok))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed

float fqtty=Float.parseFloat(this.qtty.getText());
float fprice=Float.parseFloat(this.price.getText());
float fpriceorig=Float.parseFloat(this.price1.getText());
int iopid=Integer.parseInt(((MySimleInputByCombo)this.optype).getVc2bySelected());
int ifid=Integer.parseInt(((MySimleInputByCombo)this.fidn).getVc2bySelected());
int mid=Integer.parseInt(((MySimleInputByCombo)this.menayaselect).getVc2bySelected());
CDate d=new CDate(dateButton.getDate());
if(this.completelynew)
{
 this.dealid=addnewdealtodeal(folderid,mid); 
}
adddeal(this.dealid,d,iopid,ifid,fqtty,fprice,fpriceorig);
this.dispose();
}//GEN-LAST:event_okActionPerformed

private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
this.dispose();
}//GEN-LAST:event_closeActionPerformed

private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
price1.setText(price.getText());
}//GEN-LAST:event_priceActionPerformed

private void price1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_price1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addDeal(0,"").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private CalendarForms.DateButton dateButton;
    private javax.swing.JLabel dealidname;
    private javax.swing.JComboBox fidn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox menayaselect;
    private javax.swing.JButton ok;
    private javax.swing.JComboBox optype;
    private javax.swing.JTextField price;
    private javax.swing.JTextField price1;
    private javax.swing.JTextField qtty;
    // End of variables declaration//GEN-END:variables

}
