import CDate.CDate;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import tikunimbemasad.TikunNetunNoAmount;
import tikunimbemasad.TikunNetunYahoo1;
/*
 * AppSettingsNB.java
 *
 * Created on 16 ספטמבר 2006, 09:34
 */

/**
 *
 * @author  Student
 */
public class AppSettingsNB extends javax.swing.JPanel {
    
    DBSettingsNB dbF=null;
    String timgdir=BursaAnalizer_Frame.getImgDir();
    private sqltoolNB sqlexecp;
    
    /** Creates new form AppSettingsNB */
    public AppSettingsNB() {
        initComponents();
        autoUpdate.setSelected((Boolean.valueOf(BursaAnalizer_Frame.p.getProperty("update.auto", "false"))).booleanValue());
        autoscaleyahooatupdate=Boolean.parseBoolean(BursaAnalizer_Frame.p.getProperty("autoscale.yahooatupdate","false"));
         yahooscale.setSelected(autoscaleyahooatupdate);
         autoscaleyahooatupdatefactor=Float.parseFloat(BursaAnalizer_Frame.p.getProperty("autoscale.yahooatupdate.factor","1.0"));
         if(autoscaleyahooatupdatefactor==1.0f)
                     yahooscale1x1.setSelected(true);
         else yahooscaled100.setSelected(true);
            boolean yahooatupdate;
            boolean taseupdate;
            boolean otherupdate;
            String otherstringupdate="";
         yahooatupdate=Boolean.parseBoolean(BursaAnalizer_Frame.p.getProperty("update.USEYAHOO","false"));
         taseupdate=Boolean.parseBoolean(BursaAnalizer_Frame.p.getProperty("update.USETASE","true"));
         otherupdate=Boolean.parseBoolean(BursaAnalizer_Frame.p.getProperty("update.USEOTHER","false"));
         otherstringupdate=BursaAnalizer_Frame.p.getProperty("update.USEOTHER.MODULE","none");
         othersourceupdatemodname.setVisible(false);
         jPanel3.setVisible(false);
         if(yahooatupdate)
         {
             jRadioButton2.setSelected(true);
             jPanel3.setVisible(true);
         }
         if(taseupdate)jRadioButton1.setSelected(true);
         if(otherupdate)
         {
             jRadioButton3.setSelected(true);
          othersourceupdatemodname.setText(otherstringupdate);
          othersourceupdatemodname.setVisible(true);
          
         }

         DTSRUNSTR.setText(BursaAnalizer_Frame.p.getProperty("update.DTSRUN"));
         
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        update = new javax.swing.JButton();
        autoUpdate = new javax.swing.JCheckBox();
        databases = new javax.swing.JButton();
        showlogger = new javax.swing.JCheckBox();
        tabsontopright = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        fix1 = new javax.swing.JButton();
        dateButtonfix = new CalendarForms.DateButton();
        scaleusedfix = new javax.swing.JCheckBox();
        deleteupdatefix = new javax.swing.JCheckBox();
        dateequgreater = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        yahooscale = new javax.swing.JCheckBox();
        sfactorpanel = new javax.swing.JPanel();
        yahooscaled100 = new javax.swing.JRadioButton();
        yahooscale1x1 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        othersourceupdatemodname = new javax.swing.JTextField();
        DTSRUN = new javax.swing.JButton();
        DTSRUNSTR = new javax.swing.JTextField();
        dateButtonDTS = new CalendarForms.DateButton();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Local Data Base", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 0, 204))); // NOI18N

        update.setIcon(new javax.swing.ImageIcon(timgdir+"data_refresh.png"));
        update.setText("Manual");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        autoUpdate.setText("Auto On Start");
        autoUpdate.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        autoUpdate.setMargin(new java.awt.Insets(0, 0, 0, 0));
        autoUpdate.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                autoUpdateStateChanged(evt);
            }
        });

        databases.setIcon(new javax.swing.ImageIcon(timgdir+"db.Schema.many_32x32.png"));
        databases.setText("Data Base");
        databases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databasesActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(databases)
                    .add(update)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(21, 21, 21)
                        .add(autoUpdate)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(databases)
                .add(40, 40, 40)
                .add(autoUpdate)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 40, Short.MAX_VALUE)
                .add(update)
                .addContainerGap())
        );

        showlogger.setSelected((Boolean.valueOf(BursaAnalizer_Frame.p.getProperty("logger.auto", "false"))).booleanValue());
        showlogger.setText("Show Logger");
        showlogger.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        showlogger.setMargin(new java.awt.Insets(0, 0, 0, 0));
        showlogger.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                showloggerStateChanged(evt);
            }
        });

        tabsontopright.setSelected((Boolean.valueOf(BursaAnalizer_Frame.p.getProperty("tabs.RT", "true"))).booleanValue());
        tabsontopright.setText("Tabs On Top/Right");
        tabsontopright.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        tabsontopright.setMargin(new java.awt.Insets(0, 0, 0, 0));
        tabsontopright.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabsontoprightStateChanged(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fix all entrys on some date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bookman Old Style", 3, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        fix1.setText("fix");
        fix1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fix1ActionPerformed(evt);
            }
        });

        scaleusedfix.setText("Scale?");
        scaleusedfix.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        scaleusedfix.setMargin(new java.awt.Insets(0, 0, 0, 0));

        deleteupdatefix.setText("update/delete");
        deleteupdatefix.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        deleteupdatefix.setMargin(new java.awt.Insets(0, 0, 0, 0));

        dateequgreater.setText("Date equ or >=");
        dateequgreater.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        dateequgreater.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(fix1)
                        .add(17, 17, 17)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(dateequgreater)
                            .add(dateButtonfix, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(scaleusedfix)
                        .add(15, 15, 15)
                        .add(deleteupdatefix)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(fix1)
                    .add(dateButtonfix, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(20, 20, 20)
                .add(dateequgreater)
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(scaleusedfix)
                    .add(deleteupdatefix)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("YAHOO updater setings"));

        yahooscale.setText("enable scale");
        yahooscale.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        yahooscale.setMargin(new java.awt.Insets(0, 0, 0, 0));
        yahooscale.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                yahooscaleStateChanged(evt);
            }
        });

        sfactorpanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 2, true), "Factor"));

        buttonGroup1.add(yahooscaled100);
        yahooscaled100.setText("x0.01");
        yahooscaled100.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        yahooscaled100.setMargin(new java.awt.Insets(0, 0, 0, 0));
        yahooscaled100.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yahooscaled100ItemStateChanged(evt);
            }
        });
        yahooscaled100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yahooscaled100ActionPerformed(evt);
            }
        });

        buttonGroup1.add(yahooscale1x1);
        yahooscale1x1.setText("x1.0");
        yahooscale1x1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        yahooscale1x1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        yahooscale1x1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yahooscale1x1ItemStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout sfactorpanelLayout = new org.jdesktop.layout.GroupLayout(sfactorpanel);
        sfactorpanel.setLayout(sfactorpanelLayout);
        sfactorpanelLayout.setHorizontalGroup(
            sfactorpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(sfactorpanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(sfactorpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(yahooscaled100)
                    .add(yahooscale1x1))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        sfactorpanelLayout.setVerticalGroup(
            sfactorpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(sfactorpanelLayout.createSequentialGroup()
                .add(yahooscaled100)
                .add(19, 19, 19)
                .add(yahooscale1x1)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(yahooscale)
                .add(33, 33, 33)
                .add(sfactorpanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(sfactorpanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(yahooscale))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Update from resource", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("TASE TACTS");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("YAHOO");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("OTHER");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        othersourceupdatemodname.setText("none");
        othersourceupdatemodname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                othersourceupdatemodnameActionPerformed(evt);
            }
        });
        othersourceupdatemodname.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                othersourceupdatemodnameInputMethodTextChanged(evt);
            }
        });

        DTSRUN.setText("DTS-RUN");
        DTSRUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DTSRUNActionPerformed(evt);
            }
        });

        DTSRUNSTR.setText("none");
        DTSRUNSTR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                DTSRUNSTRFocusLost(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jRadioButton1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jRadioButton2))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel4Layout.createSequentialGroup()
                                .add(DTSRUN)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(DTSRUNSTR, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel4Layout.createSequentialGroup()
                                .add(jRadioButton3)
                                .add(18, 18, 18)
                                .add(othersourceupdatemodname)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(dateButtonDTS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButton1)
                    .add(jRadioButton2))
                .add(18, 18, 18)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButton3)
                    .add(othersourceupdatemodname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(DTSRUN)
                    .add(DTSRUNSTR, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(dateButtonDTS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Pike Fix"));

        jButton1.setText("Run Wizard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("NoAmount Fix");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jButton3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton3)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jButton2.setText("SQL/JS utilite");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(36, 36, 36)
                                .add(tabsontopright)
                                .add(42, 42, 42)
                                .add(showlogger))
                            .add(layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(layout.createSequentialGroup()
                        .add(19, 19, 19)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 80, Short.MAX_VALUE)
                                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(81, 81, 81)
                                .add(jButton2)))))
                .add(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(22, 22, 22)
                        .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(22, 22, 22)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(showlogger)
                            .add(tabsontopright))))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(19, 19, 19)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(28, 28, 28)
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(35, 35, 35)
                        .add(jButton2)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void yahooscale1x1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yahooscale1x1ItemStateChanged

        if(yahooscale1x1.isSelected())
        {autoscaleyahooatupdatefactor=1.0f;
         BursaAnalizer_Frame.p.setProperty("autoscale.yahooatupdate.factor",""+autoscaleyahooatupdatefactor);
        }
    }//GEN-LAST:event_yahooscale1x1ItemStateChanged

    private void yahooscaled100ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yahooscaled100ItemStateChanged
        if(yahooscaled100.isSelected())
        {autoscaleyahooatupdatefactor=0.01f;
         BursaAnalizer_Frame.p.setProperty("autoscale.yahooatupdate.factor",""+autoscaleyahooatupdatefactor);
        }
    }//GEN-LAST:event_yahooscaled100ItemStateChanged
    private boolean autoscaleyahooatupdate=false;
    private float autoscaleyahooatupdatefactor=1.0f;
    public float getYahooScaleFactor()
    {if(yahooscale.isSelected())return autoscaleyahooatupdatefactor;
        else return 1.0f;
    }
    private void yahooscaleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_yahooscaleStateChanged

		if (((JCheckBox)evt.getSource()).isSelected())autoscaleyahooatupdate=true;
                else autoscaleyahooatupdate=false;
                BursaAnalizer_Frame.p.setProperty("autoscale.yahooatupdate", (Boolean.valueOf(autoscaleyahooatupdate)).toString());
    }//GEN-LAST:event_yahooscaleStateChanged

    private void fix1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fix1ActionPerformed
     CDate tnd=new CDate(dateButtonfix.getDate());
     
        TikunNetunYahoo1 ty=new TikunNetunYahoo1(BursaAnalizer_Frame.getConnectToDB(BursaAnalizer_Frame.DBID_BASE),
                                                                                                              BursaAnalizer_Frame.getConnectToDB(BursaAnalizer_Frame.DBID_DATA),
                                                                                                                tnd,deleteupdatefix.isSelected(),dateequgreater.isSelected());
        ty.dorun();
    }//GEN-LAST:event_fix1ActionPerformed

    private void tabsontoprightStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabsontoprightStateChanged
    boolean stat=false;
		if (((JCheckBox)evt.getSource()).isSelected())stat=true;
        BursaAnalizer_Frame.p.setProperty("tabs.RT", (Boolean.valueOf(stat)).toString());
        	BursaAnalizer_Frame.getInstance().mySetTabsPlacement(stat);
    }//GEN-LAST:event_tabsontoprightStateChanged

    private void showloggerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_showloggerStateChanged
  boolean stat=false;
		if (((JCheckBox)evt.getSource()).isSelected())stat=true;
        BursaAnalizer_Frame.p.setProperty("logger.auto", (Boolean.valueOf(stat)).toString());
        	BursaAnalizer_Frame.getInstance().showLogger(stat);
    }//GEN-LAST:event_showloggerStateChanged

    private void autoUpdateStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_autoUpdateStateChanged
   boolean stat=false;
		if (((JCheckBox)evt.getSource()).isSelected())stat=true;
    BursaAnalizer_Frame.p.setProperty("update.auto", (Boolean.valueOf(stat)).toString());
    }//GEN-LAST:event_autoUpdateStateChanged

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
    BursaAnalizer_Frame.check_constinguesy(true);
        	StockListNB sl=BursaAnalizer_Frame.getStoksListInstance();
        	sl.sltp.slt.fetchdata(null);
    }//GEN-LAST:event_updateActionPerformed

    private void databasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databasesActionPerformed
    if(dbF==null)dbF=new DBSettingsNB();
        	dbF.setVisible(true);
    }//GEN-LAST:event_databasesActionPerformed

    private void jRadioButton2ActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton2ActionPerformed
    {//GEN-HEADEREND:event_jRadioButton2ActionPerformed
        boolean stat=false;
	if (jRadioButton2.isSelected())
        {
            stat=true;
            this.jPanel3.setVisible(true);
            othersourceupdatemodname.setVisible(false);
            BursaAnalizer_Frame.p.setProperty("update.USEYAHOO", (Boolean.valueOf(stat)).toString());
        BursaAnalizer_Frame.p.setProperty("update.USETASE", (Boolean.valueOf(!stat)).toString());
        BursaAnalizer_Frame.p.setProperty("update.USEOTHER", (Boolean.valueOf(!stat)).toString());
        }
        
        
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton3ActionPerformed
    {//GEN-HEADEREND:event_jRadioButton3ActionPerformed
        boolean stat=false;
	if (jRadioButton3.isSelected())
        {
            stat=true;
            othersourceupdatemodname.setVisible(true);
            this.jPanel3.setVisible(false);
            BursaAnalizer_Frame.p.setProperty("update.USEOTHER", (Boolean.valueOf(stat)).toString());        
        BursaAnalizer_Frame.p.setProperty("update.USETASE", (Boolean.valueOf(!stat)).toString());        
        BursaAnalizer_Frame.p.setProperty("update.USEYAHOO", (Boolean.valueOf(!stat)).toString());        
        }
        
       
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton1ActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton1ActionPerformed
    {//GEN-HEADEREND:event_jRadioButton1ActionPerformed
        boolean stat=false;
	if (jRadioButton1.isSelected())
        {
            stat=true;
            othersourceupdatemodname.setVisible(false);
            this.jPanel3.setVisible(false);
            BursaAnalizer_Frame.p.setProperty("update.USETASE", (Boolean.valueOf(stat)).toString());
            BursaAnalizer_Frame.p.setProperty("update.USEYAHOO", (Boolean.valueOf(!stat)).toString());
            BursaAnalizer_Frame.p.setProperty("update.USEOTHER", (Boolean.valueOf(!stat)).toString());
        }
        
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void yahooscaled100ActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_yahooscaled100ActionPerformed
    {//GEN-HEADEREND:event_yahooscaled100ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yahooscaled100ActionPerformed

    private void othersourceupdatemodnameActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_othersourceupdatemodnameActionPerformed
    {//GEN-HEADEREND:event_othersourceupdatemodnameActionPerformed
        
    }//GEN-LAST:event_othersourceupdatemodnameActionPerformed

    private void othersourceupdatemodnameInputMethodTextChanged (java.awt.event.InputMethodEvent evt)//GEN-FIRST:event_othersourceupdatemodnameInputMethodTextChanged
    {//GEN-HEADEREND:event_othersourceupdatemodnameInputMethodTextChanged
        BursaAnalizer_Frame.p.setProperty("update.USEOTHER.MODULE", othersourceupdatemodname.getText());
    }//GEN-LAST:event_othersourceupdatemodnameInputMethodTextChanged

     FixPikeWizNB fixpikswiz=null;
    
    private void jButton1ActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        if(fixpikswiz==null)fixpikswiz=new FixPikeWizNB(this);
        fixpikswiz.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 sqlexecp=new sqltoolNB();
 sqlexecp.setVisible(true);
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
TikunNetunNoAmount tna=new TikunNetunNoAmount(BursaAnalizer_Frame.getConnectToDB(BursaAnalizer_Frame.DBID_BASE),
                                                                                                              BursaAnalizer_Frame.getConnectToDB(BursaAnalizer_Frame.DBID_DATA));
tna.dorun();
}//GEN-LAST:event_jButton3ActionPerformed

private void DTSRUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DTSRUNActionPerformed
    String prog=DTSRUNSTR.getText();
     CDate paramdate=new CDate(dateButtonDTS.getDate());
     String td=paramdate.toStringDelimitedSQLANSI('-');
   File file = new File("C:\\\\SDI_BATool\\data\\DTS\\DTSRUN\\initrun.txt");
    BufferedWriter output;
        try {
            output = new BufferedWriter(new FileWriter(file));
            output.write(td+";C:\\\\SDI_BATool\\data\\TASEDATA\\");
            output.close();
        } catch (IOException ex) {
            Logger.getLogger(AppSettingsNB.class.getName()).log(Level.SEVERE, null, ex);
        }

     String exec="cmd.exe /C start ";
     exec+=DTSRUNSTR.getText();
     System.out.println("runing\n"+exec);
     Runtime r = Runtime.getRuntime();
     Process p;
        try {
            p = r.exec(exec);
			BufferedReader stdError = new BufferedReader(new
	                 InputStreamReader(p.getErrorStream()));
			System.out.println("Here is the standard error of the command (if any):\n");
			String s="";
            while ((s = stdError.readLine()) != null)
            {
                System.out.println(s);
            }
            } catch (IOException ex) {
            Logger.getLogger(AppSettingsNB.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_DTSRUNActionPerformed

private void DTSRUNSTRFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DTSRUNSTRFocusLost
    BursaAnalizer_Frame.p.setProperty("update.DTSRUN", DTSRUNSTR.getText());
}//GEN-LAST:event_DTSRUNSTRFocusLost
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DTSRUN;
    private javax.swing.JTextField DTSRUNSTR;
    private javax.swing.JCheckBox autoUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton databases;
    private CalendarForms.DateButton dateButtonDTS;
    private CalendarForms.DateButton dateButtonfix;
    private javax.swing.JCheckBox dateequgreater;
    private javax.swing.JCheckBox deleteupdatefix;
    private javax.swing.JButton fix1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField othersourceupdatemodname;
    private javax.swing.JCheckBox scaleusedfix;
    private javax.swing.JPanel sfactorpanel;
    private javax.swing.JCheckBox showlogger;
    private javax.swing.JCheckBox tabsontopright;
    private javax.swing.JButton update;
    private javax.swing.JCheckBox yahooscale;
    private javax.swing.JRadioButton yahooscale1x1;
    private javax.swing.JRadioButton yahooscaled100;
    // End of variables declaration//GEN-END:variables
    
}
