
import Utils.TDoc;

/*
 * FilterFindPanel.java
 *
 * Created on April 2, 2007, 8:20 PM
 */
import javax.swing.ImageIcon;
import javax.swing.ListSelectionModel;

/**
 *
 * @author  Dmitry
 */
public class FilterFindPanel extends javax.swing.JPanel
{
    StockListNB parent=null;
    /** Creates new form FilterFindPanel */
    public FilterFindPanel ()
    {
        
        initComponents ();
    }
    public void setparent(StockListNB p){parent=p;}
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPFind = new javax.swing.JPanel();
        findcriteria = new javax.swing.JTextField();
        jrbbyindustry = new javax.swing.JRadioButton();
        jrbbymarket = new javax.swing.JRadioButton();
        jrb_bysymbol = new javax.swing.JRadioButton();
        Find = new javax.swing.JButton();
        Next = new javax.swing.JButton();
        updatable = new javax.swing.JCheckBox();
        Filter = new javax.swing.JPanel();
        showstok = new javax.swing.JCheckBox();
        showoptions = new javax.swing.JCheckBox();
        showother = new javax.swing.JCheckBox();

        jPFind.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search by", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 255))); // NOI18N

        buttonGroup1.add(jrbbyindustry);
        jrbbyindustry.setText("Industry");
        jrbbyindustry.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrbbyindustry.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup1.add(jrbbymarket);
        jrbbymarket.setText("Market");
        jrbbymarket.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrbbymarket.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup1.add(jrb_bysymbol);
        jrb_bysymbol.setSelected(true);
        jrb_bysymbol.setText("Symbol");
        jrb_bysymbol.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrb_bysymbol.setMargin(new java.awt.Insets(0, 0, 0, 0));

        String timgdir=BursaAnalizer_Frame.getImgDir();
        Find.setText("Find");
        Find.setIcon (new ImageIcon(timgdir+"data_find.png"));
        Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindActionPerformed(evt);
            }
        });

        Next.setText("Next");

        updatable.setText("updatable");

        org.jdesktop.layout.GroupLayout jPFindLayout = new org.jdesktop.layout.GroupLayout(jPFind);
        jPFind.setLayout(jPFindLayout);
        jPFindLayout.setHorizontalGroup(
            jPFindLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPFindLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPFindLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPFindLayout.createSequentialGroup()
                        .add(Find)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 15, Short.MAX_VALUE)
                        .add(jrb_bysymbol)
                        .add(19, 19, 19)
                        .add(jrbbyindustry)
                        .add(24, 24, 24)
                        .add(jrbbymarket))
                    .add(Next))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPFindLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(findcriteria, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 185, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(updatable))
                .addContainerGap())
        );

        jPFindLayout.linkSize(new java.awt.Component[] {Find, Next}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPFindLayout.setVerticalGroup(
            jPFindLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPFindLayout.createSequentialGroup()
                .add(jPFindLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPFindLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPFindLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jrbbyindustry)
                            .add(jrbbymarket)
                            .add(jrb_bysymbol)
                            .add(findcriteria, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPFindLayout.createSequentialGroup()
                        .add(Find)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Next)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPFindLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .add(updatable)
                .addContainerGap())
        );

        Filter.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Show", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        showstok.setText("Stock");
        showstok.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        showstok.setMargin(new java.awt.Insets(0, 0, 0, 0));

        showoptions.setText("Option");
        showoptions.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        showoptions.setMargin(new java.awt.Insets(0, 0, 0, 0));

        showother.setText("Other");
        showother.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        showother.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout FilterLayout = new org.jdesktop.layout.GroupLayout(Filter);
        Filter.setLayout(FilterLayout);
        FilterLayout.setHorizontalGroup(
            FilterLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(FilterLayout.createSequentialGroup()
                .addContainerGap()
                .add(FilterLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(showstok)
                    .add(showoptions)
                    .add(showother))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        FilterLayout.setVerticalGroup(
            FilterLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(FilterLayout.createSequentialGroup()
                .add(showstok)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(showoptions)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(showother)
                .add(1, 1, 1))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPFind, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(Filter, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPFind, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(Filter, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

private void FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindActionPerformed
String fc=this.findcriteria.getText();
String filter[]={"","","",""};
if(this.jrb_bysymbol.isSelected())
{
    filter[1]=fc;
    //parent.sltp.slt.fetchdata(filter);
}
if(this.jrbbymarket.isSelected())
{
    filter[0]=fc;
    //parent.sltp.slt.fetchdata(filter);
}
if(this.jrbbyindustry.isSelected())
{
    filter[2]=fc;
    //parent.sltp.slt.fetchdata(filter);
}
if(this.updatable.isSelected())
{
    filter[3]="1";

}
parent.sltp.slt.fetchdata(filter);
 
}//GEN-LAST:event_FindActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Filter;
    private javax.swing.JButton Find;
    private javax.swing.JButton Next;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField findcriteria;
    private javax.swing.JPanel jPFind;
    private javax.swing.JRadioButton jrb_bysymbol;
    private javax.swing.JRadioButton jrbbyindustry;
    private javax.swing.JRadioButton jrbbymarket;
    private javax.swing.JCheckBox showoptions;
    private javax.swing.JCheckBox showother;
    private javax.swing.JCheckBox showstok;
    private javax.swing.JCheckBox updatable;
    // End of variables declaration//GEN-END:variables
    
}
