/*
 * FundamentalAnaSettingsDetector.java
 *
 * Created on 19 аевеси 2006, 21:21
 */

/**
 *
 * @author  Student
 */
public class FundamentalAnaSettingsDetector extends javax.swing.JPanel {
    
    /**
     * Creates new form FundamentalAnaSettingsDetector
     */
    public FundamentalAnaSettingsDetector() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel11 = new javax.swing.JLabel();
        useCDRtest = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        CDRtestLimit = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        useYEtest = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        YEtestLimit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        useROCtest = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        ROCtestLimit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        useCFRRtest = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        CFRRtestLimit = new javax.swing.JTextField();

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 12));
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("3.");

        useCDRtest.setText("USE");
        useCDRtest.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        useCDRtest.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel12.setText("CDR=Cash/(ST Debt + LT Debt)>");
        jLabel12.setToolTipText("(Cash-Debt Ratio)-\u05de\u05e8\u05d5\u05d5\u05d7 \u05d1\u05d9\u05d8\u05d7\u05d5\u05df \u05db\u05e1\u05e4\u05d9 \u05de\u05e1\u05e4\u05d9\u05e7 \u05d2\u05d3\u05d5\u05dc \u05d1\u05de\u05e7\u05e8\u05d4 \u05e9\u05dc \u05d4\u05ea\u05e7\u05dc\u05d5\u05ea \u05d1\u05d1\u05e2\u05d9\u05d5\u05ea \u05e4\u05d9\u05e0\u05e0\u05e1\u05d9\u05d5\u05ea \u05d0\u05d5 \u05d0\u05d7\u05e8\u05d5\u05ea");

        CDRtestLimit.setText("1.5");

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 2, 1, new java.awt.Color(204, 102, 0)));
        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 12));
        jLabel15.setForeground(new java.awt.Color(0, 0, 255));
        jLabel15.setText("4.");

        useYEtest.setText("USE");
        useYEtest.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        useYEtest.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel16.setText("YE=EBIT/Enterprise Value>");
        jLabel16.setToolTipText("(Earning Yield)-");

        YEtestLimit.setText("0.5");

        jLabel2.setText("Enterprise Value=(Available Cash+ST Invests)-Market Capitalization+Total Debt");

        jLabel3.setText("Total Debt=ST Debt + LT Debt");

        jLabel4.setText("Market Capitalization=Stok Price*qtty");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel15)
                        .add(14, 14, 14)
                        .add(useYEtest))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel16)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(YEtestLimit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel3)
                        .add(71, 71, 71)
                        .add(jLabel4))
                    .add(jLabel2))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel15)
                    .add(useYEtest))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel16)
                    .add(YEtestLimit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(17, 17, 17)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel2)
                .add(20, 20, 20))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12));
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("1.");

        useROCtest.setText("USE");
        useROCtest.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        useROCtest.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel6.setText("ROK=EBIT/( Total Assets\u2013Excess Cash\u2013NIBCL)>=");
        jLabel6.setToolTipText("\u05ea\u05e9\u05d5\u05d0\u05d4 \u05e2\u05dc \u05d4\u05d4\u05e9\u05e7\u05e2\u05d4 (Return on Capital)");

        ROCtestLimit.setText("0.2");

        jLabel8.setText("NIBCL=Non Interest Bearing Current Liabilities");
        jLabel8.setToolTipText("NIBCL can be aproximated by 20% yearly of Total current liabilities");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(useROCtest))
                    .add(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(ROCtestLimit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel8)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(useROCtest)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(ROCtestLimit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel8)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12));
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("2.");

        useCFRRtest.setText("USE");
        useCFRRtest.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        useCFRRtest.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel7.setText("CFRR=(Operating Cash Flow \u2013 Capital Expenditure)/Last Year Revenues>=");
        jLabel7.setToolTipText(" (Cash Flow-Revenues Ratio)-\u05db\u05de\u05d4 \u05db\u05e1\u05e3 \u05de\u05d6\u05d5\u05de\u05df \u05e2\u05d5\u05d3\u05e3 \u05d6\u05e8\u05dd \u05dc\u05d7\u05d1\u05e8\u05d4 \u05db\u05ea\u05d5\u05e6\u05d0\u05d4 \u05de\u05d4\u05de\u05db\u05d9\u05e8\u05d5\u05ea \u05e9\u05dc\u05d4");

        CFRRtestLimit.setText("0.1");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel5)
                    .add(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(CFRRtestLimit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(useCFRRtest)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jLabel5)
                .add(8, 8, 8)
                .add(useCFRRtest)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(CFRRtestLimit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(jLabel11)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(useCDRtest))
                    .add(layout.createSequentialGroup()
                        .add(jLabel12)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(CDRtestLimit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel11)
                    .add(useCDRtest))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12)
                    .add(CDRtestLimit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(56, 56, 56)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CDRtestLimit;
    private javax.swing.JTextField CFRRtestLimit;
    private javax.swing.JTextField ROCtestLimit;
    private javax.swing.JTextField YEtestLimit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox useCDRtest;
    private javax.swing.JCheckBox useCFRRtest;
    private javax.swing.JCheckBox useROCtest;
    private javax.swing.JCheckBox useYEtest;
    // End of variables declaration//GEN-END:variables
    
}
