import CDate.CDate;
import Utils.DnldURL;
import Utils.SimpleHelp;
import java.awt.Rectangle;
import javax.swing.AbstractButton;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import myCForms.TGraph;
/*
 * GeneralyRU.java
 *
 * Created on October 27, 2006, 1:46 PM
 */

/**
 *
 * @author  Dmitry
 */
//TODO implement all this stuff 
public class GeneralyRU extends javax.swing.JFrame {
    
    /** Creates new form GeneralyRU */
    public GeneralyRU() {
        
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        close = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        totalvoted = new javax.swing.JLabel();
        tGraph1 = new myCForms.TGraph();
        hni = new javax.swing.JRadioButton();
        vba = new javax.swing.JRadioButton();
        nsb = new javax.swing.JRadioButton();
        ga = new javax.swing.JRadioButton();
        vg = new javax.swing.JRadioButton();
        hf = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ideas = new javax.swing.JTextArea();
        vote = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLabel1.setFont(new java.awt.Font("Academy Engraved LET", 2, 18));
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Register FREE or ReNew for FREE");

        jTextArea1.setBackground(new java.awt.Color(255, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Book Antiqua", 3, 18));
        jTextArea1.setForeground(new java.awt.Color(102, 102, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(4);
        jTextArea1.setText("Since it is free software !!! Only we ask it is a-\n1) count of real satisfied users :)))\nand \n2) feedbak :)\nSo please Vote and SEND\n!!!! You CAN BE ANONIMOUS !!!");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 255, 153)));
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                closeActionPerformed(evt);
            }
        });

        jLabel4.setText("Total voted:");

        totalvoted.setText("0");

        org.jdesktop.layout.GroupLayout tGraph1Layout = new org.jdesktop.layout.GroupLayout(tGraph1);
        tGraph1.setLayout(tGraph1Layout);
        tGraph1Layout.setHorizontalGroup(
            tGraph1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 252, Short.MAX_VALUE)
        );
        tGraph1Layout.setVerticalGroup(
            tGraph1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 149, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(26, 26, 26)
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(totalvoted))
                    .add(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(tGraph1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(tGraph1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 153, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 166, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(totalvoted))
                .addContainerGap())
        );

        hni.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup1.add(hni);
        hni.setText("have no idea");
        hni.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        hni.setMargin(new java.awt.Insets(0, 0, 0, 0));
        hni.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                hniStateChanged(evt);
            }
        });

        vba.setBackground(new java.awt.Color(51, 255, 255));
        buttonGroup1.add(vba);
        vba.setText("verry bad actions");
        vba.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        vba.setMargin(new java.awt.Insets(0, 0, 0, 0));
        vba.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                vbaStateChanged(evt);
            }
        });

        nsb.setBackground(new java.awt.Color(51, 51, 255));
        buttonGroup1.add(nsb);
        nsb.setText("not so bad");
        nsb.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        nsb.setMargin(new java.awt.Insets(0, 0, 0, 0));
        nsb.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                nsbStateChanged(evt);
            }
        });

        ga.setBackground(new java.awt.Color(204, 0, 204));
        buttonGroup1.add(ga);
        ga.setSelected(true);
        ga.setText("good anouth");
        ga.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ga.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ga.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                gaStateChanged(evt);
            }
        });

        vg.setBackground(new java.awt.Color(255, 255, 0));
        buttonGroup1.add(vg);
        vg.setText("verry good");
        vg.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        vg.setMargin(new java.awt.Insets(0, 0, 0, 0));
        vg.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                vgStateChanged(evt);
            }
        });

        hf.setBackground(new java.awt.Color(0, 255, 51));
        buttonGroup1.add(hf);
        hf.setText("have future");
        hf.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        hf.setMargin(new java.awt.Insets(0, 0, 0, 0));
        hf.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                hfStateChanged(evt);
            }
        });

        jLabel2.setText("E-mail or jus nik:");

        mail.setText("your@mail.com");

        jLabel3.setText("Some ideas?:");

        ideas.setColumns(20);
        ideas.setRows(5);
        jScrollPane2.setViewportView(ideas);

        vote.setText("Vote");
        vote.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                voteActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("* You can be anonimous");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 21, Short.MAX_VALUE)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(179, 179, 179)
                                        .add(vote)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(close))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(24, 24, 24)
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 297, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jLabel3)
                                            .add(jPanel1Layout.createSequentialGroup()
                                                .add(mail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(jLabel5))
                                            .add(jLabel2)
                                            .add(hf)
                                            .add(vg)
                                            .add(ga)
                                            .add(nsb)
                                            .add(vba)
                                            .add(hni)))))
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(60, 60, 60)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 500, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 144, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(54, 54, 54)
                        .add(hni)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(vba)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(nsb)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(ga)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(vg)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(hf)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(mail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel5))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(14, 14, 14)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(close)
                            .add(vote)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hfStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hfStateChanged
    if (((JRadioButton)evt.getSource()).isSelected())curentlyvoted=5;
    }//GEN-LAST:event_hfStateChanged

    private void vgStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_vgStateChanged
    if (((JRadioButton)evt.getSource()).isSelected())curentlyvoted=4;
    }//GEN-LAST:event_vgStateChanged

    private void gaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_gaStateChanged
    if (((JRadioButton)evt.getSource()).isSelected())curentlyvoted=3;
    }//GEN-LAST:event_gaStateChanged

    private void nsbStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nsbStateChanged
    if (((JRadioButton)evt.getSource()).isSelected())curentlyvoted=2;
    }//GEN-LAST:event_nsbStateChanged

    private void vbaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_vbaStateChanged
    if (((JRadioButton)evt.getSource()).isSelected())curentlyvoted=1;
    }//GEN-LAST:event_vbaStateChanged

    private void hniStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hniStateChanged
    if (((JRadioButton)evt.getSource()).isSelected())curentlyvoted=0;
    }//GEN-LAST:event_hniStateChanged

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
    dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void voteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voteActionPerformed
     String regs="http://h.1asphost.com/hellcreator/www/projects/java/BATOOL/register.asp?mail=";
            regs+=mail.getText()+"&vote=";
            regs+=curentlyvoted+"&msg="+ideas.getText();
            //replace the spaces in parameters
            regs=regs.replace(' ','+');
            DnldURL d=new DnldURL(regs);
            //parse the asp page
            int []votes=new int[6];
            votes[0]=10;
            votes[1]=90;
            votes[2]=50;
            votes[3]=80;
            votes[4]=90;
            votes[5]=30;
        //then update graph
        CDate now=new CDate();
        BursaAnalizer_Frame.p.setProperty("ONserver.voted", now.toString());
        updateGraph(votes);
    }//GEN-LAST:event_voteActionPerformed
    
    
    private void updateGraph(int []votes)
    {
        
        TGraph tg=new TGraph();
        tg.setDataSeries(new String[]{"1","2","3"},new int[]{1,2,3});
        /*
     Rectangle r=vp0.getBounds();
     r.y=r.y-(100-votes[0]);
     r.height=votes[0];
     vp0.setBounds(r);
     r=vp1.getBounds();
     r.y=r.y-(100-votes[1]);
     r.height=votes[1];
     vp1.setBounds(r);
     r=vp2.getBounds();
     r.y=r.y-(100-votes[2]);
     r.height=votes[2];
     vp2.setBounds(r);
     r=vp3.getBounds();
     r.y=r.y-(100-votes[3]);
     r.height=votes[3];
     vp3.setBounds(r);
     r=vp4.getBounds();
     r.y=r.y-(100-votes[4]);
     r.height=votes[4];
     vp4.setBounds(r);
     r=vp5.getBounds();
     r.y=r.y-(100-votes[5]);
     r.height=votes[5];
     vp5.setBounds(r);
         */
     //repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneralyRU().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton close;
    private javax.swing.JRadioButton ga;
    private javax.swing.JRadioButton hf;
    private javax.swing.JRadioButton hni;
    private javax.swing.JTextArea ideas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField mail;
    private javax.swing.JRadioButton nsb;
    private myCForms.TGraph tGraph1;
    private javax.swing.JLabel totalvoted;
    private javax.swing.JRadioButton vba;
    private javax.swing.JRadioButton vg;
    private javax.swing.JButton vote;
    // End of variables declaration//GEN-END:variables

    private int curentlyvoted;
    
    
}
