/*
 * JDPanelAdvTools.java
 *
 * Created on October 20, 2006, 8:54 PM
 */

/**
 *
 * @author  Dmitry
 */
public class JDPanelAdvTools extends javax.swing.JPanel {
    JDPanel controllsit=null;
    /** Creates new form JDPanelAdvTools */
    public JDPanelAdvTools() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        percentruler = new javax.swing.JToggleButton();
        fibonachiruler = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        boilinger = new javax.swing.JToggleButton();
        boilingerpercents = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        boilingerdays = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();

        percentruler.setText("(%)");
        percentruler.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                percentrulerItemStateChanged(evt);
            }
        });

        fibonachiruler.setText("fib");
        fibonachiruler.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fibonachirulerItemStateChanged(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        boilinger.setFont(new java.awt.Font("Tahoma", 1, 12));
        boilinger.setText("B");
        boilinger.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boilingerItemStateChanged(evt);
            }
        });

        boilingerpercents.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        boilingerpercents.setText("5");

        jLabel1.setText("3 days");

        boilingerdays.setMaximum(30);
        boilingerdays.setMinimum(3);
        boilingerdays.setValue(7);
        boilingerdays.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                boilingerdaysStateChanged(evt);
            }
        });

        jLabel2.setText("(%)");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(boilinger)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(boilingerdays, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1)
                .add(13, 13, 13)
                .add(boilingerpercents, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(boilingerdays, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(boilinger)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel1)
                            .add(boilingerpercents, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel2))
                        .add(4, 4, 4)))
                .addContainerGap())
        );

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(percentruler)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(fibonachiruler)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 24, Short.MAX_VALUE)
                .add(clear)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(23, 23, 23)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(fibonachiruler, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(percentruler, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .add(clear)
                .add(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fibonachirulerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fibonachirulerItemStateChanged
// TODO add your handling code here:
    }//GEN-LAST:event_fibonachirulerItemStateChanged

    private void percentrulerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_percentrulerItemStateChanged
// TODO add your handling code here:
    }//GEN-LAST:event_percentrulerItemStateChanged

    private void boilingerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boilingerItemStateChanged
// TODO add your handling code here:
    }//GEN-LAST:event_boilingerItemStateChanged

    private void boilingerdaysStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_boilingerdaysStateChanged
// TODO add your handling code here:
    }//GEN-LAST:event_boilingerdaysStateChanged

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
    controllsit.pointsclickedin4.clear();
    controllsit.repaint();
    }//GEN-LAST:event_clearActionPerformed

    void setControlls(JDPanel jDPanel) {
        controllsit=jDPanel;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton boilinger;
    private javax.swing.JSlider boilingerdays;
    private javax.swing.JTextField boilingerpercents;
    private javax.swing.JButton clear;
    private javax.swing.JToggleButton fibonachiruler;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton percentruler;
    // End of variables declaration//GEN-END:variables
    
}
