
import DBCONNECT.TRS;
import StatisticBase.STA;
import TechnicalTools.MarkovitchFolderModel;
import TechnicalTools.ResistanseSupportLine;
import Utils.LoggerNB;
import Utils.MySimleInputByCombo;
import Utils.TDoc;
import charts.jbarchart;
import charts.jfpiechart;

import charts.xyscaterchart;
import java.awt.Component;
import java.sql.Connection;

/*
 * stockRisk.java
 *
 * Created on 4 דצמבר 2008, 22:15
 */
import java.sql.SQLException;
import java.util.ArrayList;



/**
 *
 * @author  Dmitry
 */
public class stockRisk extends javax.swing.JPanel {
    private int uid;
    private boolean locked=true;

    /** Creates new form stockRisk */
    public stockRisk() {
        initComponents();
    }

    private void domarkononefolder(int folderid) {
        Connection con=BursaAnalizer_Frame.getConnectToDB(BursaAnalizer_Frame.DBID_USER).con;
        TRS RS =new TRS(con);
        int ti = 0;
        TDoc t = null;
        java.util.List atd2m                = new ArrayList();
        try {
            String sql="SELECT [DEAL].DEALID,[DEAL].MENAYAID,[MENAYA_BASE].[NAME],sum([OPERATIONS].QTTY*[OPERATIONS].PRICE/100.0) as s" +
                    " FROM [DEAL] inner join [OPERATIONS] on ([DEAL].DEALID=[OPERATIONS].DEALID)" +
                    "inner join [MENAYA_BASE] on ([MENAYA_BASE].MENAYA_ID=[DEAL].MENAYAID)"+
                    " WHERE [DEAL].FOLDERID=" + folderid+
                    " group by  [DEAL].DEALID,[DEAL].MENAYAID,[MENAYA_BASE].[NAME]";
            RS.execSQL(sql);

            while (RS.rs.next()) {
                t = new TDoc (4);
                t.o[0] = new Integer (RS.rs.getInt(1));//dealid
                t.o[1] = new Integer(RS.rs.getInt(2));//menayaid
                t.o[3] = new String(RS.rs.getString(3));//menaya name
                t.o[2]=new Float(RS.rs.getFloat(4));//sum
                atd2m.add(t);
                java.util.List atd               = new ArrayList();
                GenericTableLoaders.loadTradeDataTableToOut(7, ((Integer)t.o[1] ).intValue(), atd);
                MarkovitchFolderModel m=new MarkovitchFolderModel(this.jSlider1.getValue(),"ONCLOSE"); 
                 m.run(atd);
           double         dataSRLine[]=m.getMFM();
           TDoc tt =new TDoc(5);
           tt.o[0]=t.o[3] ;//Name
           tt.o[1]=new Double(dataSRLine[2]);//Ei
           tt.o[2]=new Double(dataSRLine[1]);//real
           tt.o[3]=new Double(dataSRLine[0]);//real/Ei
           tt.o[4]=new Double(((Float)t.o[2]).doubleValue());//sum of menaya
           atdfEED.add(tt);       
            }
            
        }  catch (SQLException e) {
            if (LoggerNB.debuging){                System.out.println("Error20: " + e);}
        }   finally {
            RS.close();
            RS = null;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Recalculate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        period = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        from = new CalendarForms.DateButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        stdev = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        geom = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        onfolder = new javax.swing.JRadioButton();
        onstock = new javax.swing.JRadioButton();
        fsid = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        R1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        S1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        R2 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        S2 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        P = new javax.swing.JTextArea();
        jSlider1 = new javax.swing.JSlider();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        minBuyeqtty = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        SLP = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        ERP = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        ER = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        minRRR = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        calculatedRRR = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        bpta = new javax.swing.JTextArea();
        lsrd = new javax.swing.JLabel();
        lock = new javax.swing.JToggleButton();
        defaults = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane15 = new javax.swing.JScrollPane();
        mrtl = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        Ei = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane17 = new javax.swing.JScrollPane();
        EReal = new javax.swing.JTextArea();
        EEDistribution = new javax.swing.JButton();
        jRadioButtonpie = new javax.swing.JRadioButton();
        jRadioButtonbars = new javax.swing.JRadioButton();
        consistsof = new javax.swing.JButton();
        jButtonBuild = new javax.swing.JButton();
        jButtonmarkfolder = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane18 = new javax.swing.JScrollPane();
        msum = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(800, 800));
        setMinimumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(800, 600));

        Recalculate.setText("Calculate"); // NOI18N
        Recalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecalculateActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 5, true), "Statisics based"));

        jLabel1.setText("STDEV"); // NOI18N

        period.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Daily", "Weekly", "Last Year", "Early" }));

        jLabel2.setText("Period"); // NOI18N

        jLabel3.setText("From"); // NOI18N

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        stdev.setColumns(20);
        stdev.setEditable(false);
        stdev.setFont(new java.awt.Font("Courier New", 0, 12));
        stdev.setRows(5);
        stdev.setText("0.0"); // NOI18N
        stdev.setWrapStyleWord(true);
        stdev.setEnabled(false);
        jScrollPane1.setViewportView(stdev);

        jLabel4.setText("Geom"); // NOI18N

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        geom.setColumns(20);
        geom.setEditable(false);
        geom.setFont(new java.awt.Font("Courier New", 0, 12));
        geom.setRows(5);
        geom.setText("0.0"); // NOI18N
        geom.setWrapStyleWord(true);
        geom.setEnabled(false);
        jScrollPane2.setViewportView(geom);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(period, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(period, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        buttonGroup1.add(onfolder);
        onfolder.setText("On Folder"); // NOI18N
        onfolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onfolderActionPerformed(evt);
            }
        });

        buttonGroup1.add(onstock);
        onstock.setSelected(true);
        onstock.setText("On Stock"); // NOI18N
        onstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onstockActionPerformed(evt);
            }
        });

        fsid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fsid.setName("comfsid"); // NOI18N
        Connection con=BursaAnalizer_Frame.getConnectToDB(BursaAnalizer_Frame.DBID_BASE).con;
        MySimleInputByCombo cbind = new MySimleInputByCombo ();
        cbind.buildfromsource(null, con, "[MENAYA_BASE]", "NAME", "MENAYA_ID");
        this.fsid=cbind;

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fsid, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(onstock)
                        .addGap(18, 18, 18)
                        .addComponent(onfolder)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onstock)
                    .addComponent(onfolder))
                .addGap(18, 18, 18)
                .addComponent(fsid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true), "Risk Reward Ratio"));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        R1.setColumns(20);
        R1.setEditable(false);
        R1.setFont(new java.awt.Font("Courier New", 0, 12));
        R1.setRows(5);
        R1.setText("0.0"); // NOI18N
        R1.setWrapStyleWord(true);
        R1.setEnabled(false);
        jScrollPane3.setViewportView(R1);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        S1.setColumns(20);
        S1.setEditable(false);
        S1.setFont(new java.awt.Font("Courier New", 0, 12));
        S1.setRows(5);
        S1.setText("0.0"); // NOI18N
        S1.setWrapStyleWord(true);
        S1.setEnabled(false);
        jScrollPane4.setViewportView(S1);

        jLabel5.setText("R1");

        jLabel6.setText("S1");

        jLabel7.setText("R2");

        jLabel8.setText("S2");

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        R2.setColumns(20);
        R2.setEditable(false);
        R2.setFont(new java.awt.Font("Courier New", 0, 12));
        R2.setRows(5);
        R2.setText("0.0"); // NOI18N
        R2.setWrapStyleWord(true);
        R2.setEnabled(false);
        jScrollPane5.setViewportView(R2);

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        S2.setColumns(20);
        S2.setEditable(false);
        S2.setFont(new java.awt.Font("Courier New", 0, 12));
        S2.setRows(5);
        S2.setText("0.0"); // NOI18N
        S2.setWrapStyleWord(true);
        S2.setEnabled(false);
        jScrollPane6.setViewportView(S2);

        jLabel9.setText("Pivote");

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        P.setColumns(20);
        P.setEditable(false);
        P.setFont(new java.awt.Font("Courier New", 0, 12));
        P.setRows(5);
        P.setText("0.0"); // NOI18N
        P.setWrapStyleWord(true);
        P.setEnabled(false);
        jScrollPane7.setViewportView(P);

        jSlider1.setMajorTickSpacing(7);
        jSlider1.setMaximum(49);
        jSlider1.setMinimum(7);
        jSlider1.setMinorTickSpacing(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setToolTipText("Period of Support&Resistanse");
        jSlider1.setValue(7);
        jSlider1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSlider1MouseDragged(evt);
            }
        });

        jLabel10.setText("Min Buye Qtty");

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        minBuyeqtty.setColumns(20);
        minBuyeqtty.setFont(new java.awt.Font("Courier New", 0, 12));
        minBuyeqtty.setRows(5);
        minBuyeqtty.setText("1000"); // NOI18N
        minBuyeqtty.setWrapStyleWord(true);
        jScrollPane8.setViewportView(minBuyeqtty);

        jLabel11.setText("Stop Loss %");

        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane9.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        SLP.setColumns(20);
        SLP.setFont(new java.awt.Font("Courier New", 0, 12));
        SLP.setRows(5);
        SLP.setText("-5.0"); // NOI18N
        SLP.setWrapStyleWord(true);
        jScrollPane9.setViewportView(SLP);

        jLabel12.setText("Expected Reach %");

        jScrollPane10.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane10.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        ERP.setColumns(20);
        ERP.setFont(new java.awt.Font("Courier New", 0, 12));
        ERP.setRows(5);
        ERP.setText("-5.0"); // NOI18N
        ERP.setWrapStyleWord(true);
        jScrollPane10.setViewportView(ERP);

        jLabel13.setText("Expected Reach");

        jScrollPane11.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane11.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        ER.setColumns(20);
        ER.setEditable(false);
        ER.setFont(new java.awt.Font("Courier New", 0, 12));
        ER.setRows(5);
        ER.setText("0.0"); // NOI18N
        ER.setWrapStyleWord(true);
        ER.setEnabled(false);
        jScrollPane11.setViewportView(ER);

        jLabel14.setText("Min RR Ratio");

        jScrollPane12.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane12.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        minRRR.setColumns(20);
        minRRR.setFont(new java.awt.Font("Courier New", 0, 12));
        minRRR.setRows(5);
        minRRR.setText("0.33"); // NOI18N
        minRRR.setWrapStyleWord(true);
        jScrollPane12.setViewportView(minRRR);

        jLabel15.setText("Calculated RRR");

        jScrollPane13.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane13.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        calculatedRRR.setColumns(20);
        calculatedRRR.setEditable(false);
        calculatedRRR.setFont(new java.awt.Font("Courier New", 0, 12));
        calculatedRRR.setRows(5);
        calculatedRRR.setText("0.0"); // NOI18N
        calculatedRRR.setWrapStyleWord(true);
        calculatedRRR.setEnabled(false);
        jScrollPane13.setViewportView(calculatedRRR);

        jLabel16.setText("Buye Price TA");

        jScrollPane14.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane14.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        bpta.setColumns(20);
        bpta.setEditable(false);
        bpta.setFont(new java.awt.Font("Courier New", 0, 12));
        bpta.setRows(5);
        bpta.setText("0.0"); // NOI18N
        bpta.setWrapStyleWord(true);
        jScrollPane14.setViewportView(bpta);

        lsrd.setText("Support Resistance Days :");

        lock.setSelected(true);
        lock.setText("Lock");
        lock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(34, 34, 34)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(34, 34, 34)
                                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(lock, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lsrd)
                            .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(16, 16, 16))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lsrd)
                    .addComponent(lock))
                .addGap(18, 18, 18)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        defaults.setText("Defaults");

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 1, true));

        jScrollPane15.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane15.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        mrtl.setColumns(20);
        mrtl.setEditable(false);
        mrtl.setFont(new java.awt.Font("Courier New", 0, 12));
        mrtl.setRows(5);
        mrtl.setText("0.0"); // NOI18N
        mrtl.setWrapStyleWord(true);
        mrtl.setEnabled(false);
        jScrollPane15.setViewportView(mrtl);

        jLabel17.setText("Risk to Lose");

        jLabel18.setText("Ei");

        jScrollPane16.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane16.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Ei.setColumns(20);
        Ei.setEditable(false);
        Ei.setFont(new java.awt.Font("Courier New", 0, 12));
        Ei.setRows(5);
        Ei.setText("0.0"); // NOI18N
        Ei.setWrapStyleWord(true);
        Ei.setEnabled(false);
        jScrollPane16.setViewportView(Ei);

        jLabel19.setText("Real");

        jScrollPane17.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane17.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        EReal.setColumns(20);
        EReal.setEditable(false);
        EReal.setFont(new java.awt.Font("Courier New", 0, 12));
        EReal.setRows(5);
        EReal.setText("0.0"); // NOI18N
        EReal.setWrapStyleWord(true);
        EReal.setEnabled(false);
        jScrollPane17.setViewportView(EReal);

        EEDistribution.setText("EE Distribution");
        EEDistribution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EEDistributionActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButtonpie);
        jRadioButtonpie.setSelected(true);
        jRadioButtonpie.setText("Pie");
        jRadioButtonpie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonpieActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButtonbars);
        jRadioButtonbars.setText("Bars");

        consistsof.setText("Consists");
        consistsof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consistsofActionPerformed(evt);
            }
        });

        jButtonBuild.setText("Build");
        jButtonBuild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuildActionPerformed(evt);
            }
        });

        jButtonmarkfolder.setText("MarkovitchFolder");
        jButtonmarkfolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmarkfolderActionPerformed(evt);
            }
        });

        jLabel20.setText("Sum");

        jScrollPane18.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane18.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        msum.setColumns(20);
        msum.setEditable(false);
        msum.setFont(new java.awt.Font("Courier New", 0, 12));
        msum.setRows(5);
        msum.setText("0.0"); // NOI18N
        msum.setWrapStyleWord(true);
        msum.setEnabled(false);
        jScrollPane18.setViewportView(msum);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(consistsof, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EEDistribution, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonBuild, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonmarkfolder)
                                    .addComponent(jRadioButtonpie))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonbars)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EEDistribution)
                    .addComponent(jRadioButtonpie)
                    .addComponent(jRadioButtonbars))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consistsof)
                    .addComponent(jButtonmarkfolder))
                .addGap(18, 18, 18)
                .addComponent(jButtonBuild)
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Recalculate)
                            .addComponent(defaults))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Recalculate)
                                .addGap(18, 18, 18)
                                .addComponent(defaults))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)))
                .addContainerGap(320, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void onfolderallcalculate() {
        Object o[][]=((MySimleInputByCombo)fsid).getdata();
         atdfEED.clear();
        for(int i=0;i< o.length;i++)
        {
         int folderid=Integer.parseInt((String)o[i][1]);
        domarkononefolder(folderid);
        }
    }
   java.util.List atdfEED               = new ArrayList();
    private TDoc onfoldermark() {
        atdfEED.clear();
        int folderid=Integer.parseInt(
             ((MySimleInputByCombo)fsid).getVc2bySelected()
              );
        domarkononefolder(folderid);
        return avgmrtl(folderid,true);
    }
private TDoc avgmrtl(int fid,boolean upd)
{
    TDoc tt ;
    TDoc ret=new TDoc(6);
    double he[]=new double[atdfEED.size()];
    double hr[]=new double[atdfEED.size()];
    double hy[]=new double[atdfEED.size()];
    double hs[]=new double[atdfEED.size()];
   
    for (int i=0;i<atdfEED.size();i++)
    {
     tt=(TDoc)atdfEED.get(i);
     he[i]=((Double)tt.o[1]).doubleValue();
     hr[i]=((Double)tt.o[2]).doubleValue();
     hy[i]=((Double)tt.o[3]).doubleValue();
     hs[i]=((Double)tt.o[4]).doubleValue();
    }
    try
    {
      double ahe=0;
      if(he.length>0)ahe=STA.avg(he);
      double ahr=0;
      if(hr.length>0)
      ahr=STA.avg(hr);
      double ahy=0;
      if(hy.length>0)ahy=STA.avg(hy);
      double ahs=0;
      if(hs.length>0)ahs=STA.avg(hs);
      ret.o[0]=fid;
      ret.o[1]=ahe;//ei
      ret.o[2]=ahr;
      ret.o[3]=ahy;//risk
      ret.o[4]=ahs;
      if(upd)
      {
        this.Ei.setText(String.format("%1$.3f", ahe));
        this.mrtl.setText(String.format("%1$.3f",ahy));
        this.EReal.setText(String.format("%1$.3f", ahr));
        this.msum.setText(String.format("%1$.2f", ahs));
      }
    }catch(Exception e)
    {
     System.out.println("avg error occured");
       if(upd)
       {
        this.Ei.setText(String.format("%1$.2f", 0.0));
        this.mrtl.setText(String.format("%1$.2f",0.0));
        this.EReal.setText(String.format("%1$.2f", 0.0));
       }
    }
    
    
    return ret;
    
}
private void onstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onstockActionPerformed
Connection con=BursaAnalizer_Frame.getConnectToDB(BursaAnalizer_Frame.DBID_BASE).con;     
          ((MySimleInputByCombo)fsid).buildfromsource(null, con, "[MENAYA_BASE]", "NAME", "MENAYA_ID");
}//GEN-LAST:event_onstockActionPerformed

private void onfolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onfolderActionPerformed
   
    Connection con=BursaAnalizer_Frame.getConnectToDB(BursaAnalizer_Frame.DBID_USER).con;
 uid=BursaAnalizer_Frame.getUserFolderInstance().sv.getuserid();
         ((MySimleInputByCombo)fsid).buildfromsource(null, con, " [FOLDER]", "NAME", "ID", " where uid="+uid);
         
         
}//GEN-LAST:event_onfolderActionPerformed

private void RecalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecalculateActionPerformed
      atdfEED.clear();
    if(this.onstock.isSelected())
    {
    onstoksinglecalculate();
    onstoksinglemark();
    }
    else
    {
        onfolderallcalculate();
        onfoldermark();
    }
           
}//GEN-LAST:event_RecalculateActionPerformed
private void onstoksinglemark() {
        int id=Integer.parseInt(
             ((MySimleInputByCombo)fsid).getVc2bySelected()
              );
    java.util.List atd                = new ArrayList();
    GenericTableLoaders.loadTradeDataTableToOut(7, id, atd);
    MarkovitchFolderModel m=new MarkovitchFolderModel(this.jSlider1.getValue(),"ONCLOSE");
   
                    m.run(atd);
           double         dataSRLine[]=m.getMFM();
           
           this.mrtl.setText(String.format("%1$.3f", dataSRLine[0]));
           this.EReal.setText(String.format("%1$.3f", dataSRLine[1]));
           this.Ei.setText(String.format("%1$.3f", dataSRLine[2]));
           
    }
private void onstoksinglecalculate()
{
int id=Integer.parseInt(
             ((MySimleInputByCombo)fsid).getVc2bySelected()
              );
    java.util.List atd                = new ArrayList();
    GenericTableLoaders.loadTradeDataTableToOut(7, id, atd);
    ResistanseSupportLine rsl=new ResistanseSupportLine(this.jSlider1.getValue());
                    rsl.run(atd);
           double         dataSRLine[]=rsl.getRSL();
           
           this.R1.setText(String.format("%1$.3f", (float)dataSRLine[1]));
           this.R2.setText(String.format("%1$.3f", (float)dataSRLine[2]));
           this.S1.setText(String.format("%1$.3f", (float)dataSRLine[3]));
           this.S2.setText(String.format("%1$.3f", (float)dataSRLine[4]));
           this.P.setText(String.format("%1$.3f", (float)dataSRLine[0]));
           
           float bp=((Float)((TDoc)atd.get(atd.size()-1)).o[4]).floatValue();
           float bq=Float.parseFloat(this.minBuyeqtty.getText());
           
           float lerp=1.0f+(Float.parseFloat(this.ERP.getText()))/100.0f;
           this.ER.setText(String.format("%1$.3f", (float)dataSRLine[2]*lerp));
           if(locked)
           {
               bpta.setText(String.format("%1$.3f",bp));
           }else
           {
              bp=Float.parseFloat(bpta.getText());
           }
           float c=bp*bq;//buye cost
           float fc=bq*(float)dataSRLine[2]*lerp;//reach cost
           float oslc=( (float)dataSRLine[4]+ (float)dataSRLine[4]*(Float.parseFloat(this.SLP.getText()))/100.0f)*bq;//cost on stop loss
           float loss=oslc-c;
           float will=fc-c;
           float rrrrr=(loss/bq)/(will/bq);
           this.calculatedRRR.setText(String.format("%1$.3f", rrrrr));
           this.calculatedRRR.setToolTipText("Recomended Reward Risk Ratio is <= 1:3");
    
}
private void jSlider1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseDragged
this.lsrd.setText("Support Resistance Days :"+jSlider1.getValue());
}//GEN-LAST:event_jSlider1MouseDragged

private void lockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lockActionPerformed
 this.locked=!this.locked;
  bpta.setEditable(!locked);
}//GEN-LAST:event_lockActionPerformed
jfpiechart pc=null;
jbarchart bc=null;
private void EEDistributionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EEDistributionActionPerformed
 if(jRadioButtonpie.isSelected())
 {
    if(pc!=null)pc.close();
        pc=new jfpiechart("Pie Chart","התפלגות רווחי תיק",false);
        pc.setdata(atdfEED,1);
 }else
 {
 bc=new jbarchart("Bar Chart","התפלגות רווחי תיק","Stock","value",false);
  bc.setdata(atdfEED,new String[]{"Ei","Real"},1,2);
 }
}//GEN-LAST:event_EEDistributionActionPerformed

private void jRadioButtonpieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonpieActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jRadioButtonpieActionPerformed

private void consistsofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consistsofActionPerformed
onfolderallcalculate();
}//GEN-LAST:event_consistsofActionPerformed

BuildFolderFrame afbuilder=null;
private void jButtonBuildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuildActionPerformed
 if(this.afbuilder==null)
 {
  this.afbuilder=new BuildFolderFrame(this);
 }else
 {
  this.afbuilder.dispose();
  this.afbuilder=new BuildFolderFrame(this);
 }
}//GEN-LAST:event_jButtonBuildActionPerformed

 java.util.List ERGD                = new ArrayList();
private void jButtonmarkfolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmarkfolderActionPerformed
        if(onstock.isSelected())return; 
        Object o[][]=((MySimleInputByCombo)fsid).getdata();
        ERGD.clear();
        for(int i=0;i< o.length;i++)
        {
         int folderid=Integer.parseInt((String)o[i][1]);
          atdfEED.clear();
        domarkononefolder(folderid);
        TDoc ret=avgmrtl(folderid,false);
        ret.o[5]=new String((String)o[i][0]);
         ERGD.add(ret);
         
        }
         xyscaterchart xyc=new xyscaterchart("Markovitch E/R","All Folder compare E/R");
         
        xyc.setdata(ERGD, "Risk", "Earn");
        
}//GEN-LAST:event_jButtonmarkfolderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EEDistribution;
    private javax.swing.JTextArea ER;
    private javax.swing.JTextArea ERP;
    private javax.swing.JTextArea EReal;
    private javax.swing.JTextArea Ei;
    private javax.swing.JTextArea P;
    private javax.swing.JTextArea R1;
    private javax.swing.JTextArea R2;
    private javax.swing.JButton Recalculate;
    private javax.swing.JTextArea S1;
    private javax.swing.JTextArea S2;
    private javax.swing.JTextArea SLP;
    private javax.swing.JTextArea bpta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextArea calculatedRRR;
    private javax.swing.JButton consistsof;
    private javax.swing.JToggleButton defaults;
    private CalendarForms.DateButton from;
    private javax.swing.JComboBox fsid;
    private javax.swing.JTextArea geom;
    private javax.swing.JButton jButtonBuild;
    private javax.swing.JButton jButtonmarkfolder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonbars;
    private javax.swing.JRadioButton jRadioButtonpie;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JToggleButton lock;
    private javax.swing.JLabel lsrd;
    private javax.swing.JTextArea minBuyeqtty;
    private javax.swing.JTextArea minRRR;
    private javax.swing.JTextArea mrtl;
    private javax.swing.JTextArea msum;
    private javax.swing.JRadioButton onfolder;
    private javax.swing.JRadioButton onstock;
    private javax.swing.JComboBox period;
    private javax.swing.JTextArea stdev;
    // End of variables declaration//GEN-END:variables

    

}
