import DBCONNECT.Msdb_connect;
import DBCONNECT.DataBaseConnector;
import DBCONNECT.TRS;
import Utils.MySimleInputByCombo;
/*
 * StokRowEditor.java
 *
 * Created on 17 ιεμι 2006, 13:36
 */
import javax.swing.table.TableModel;

/**
 *
 * @author  student
 */
public class StokRowEditor extends javax.swing.JFrame {
    private boolean flag;
    int menayaid=0;
    
    /** Creates new form StokRowEditor */
    public StokRowEditor(boolean tflag) {
        initComponents();
        this.flag=tflag;
        if(flag==EDITFLAG)this.setTitle("Edit Stok");
        else this.setTitle("Adding New Stok");
        this.setVisible(true);
    }

    void setMenayaID(int menayaid) {
        this.menayaid=menayaid;
    }

    TableModel tm=null;
    int sr=-1;
    StoksListTable aThis=null;
    void setTM(int sr, TableModel tm, StoksListTable aThis) {
    this.tm=tm;
        this.sr=sr;
        this.aThis=aThis;
    }

    private void donewupdate() {
       if(flag==EDITFLAG)editstok();
       else newstock();
    }

    private void editstok() {
                     String sc= new Character((char)39).toString();     
                     String sqlstr_begin_upd="UPDATE MENAYA_BASE SET  ";
                     sqlstr_begin_upd+="SYMBOL="+sc+getStokSymbol()+sc;
                     sqlstr_begin_upd+=", [NAME]="+sc+getStok()+sc;
                     sqlstr_begin_upd+=", STOCKTYPE_ID="+getStokType();
                     sqlstr_begin_upd+=", COMPANY_ID="+getCompany();
                     sqlstr_begin_upd+=", MARKET_ID="+getMarket();
                     sqlstr_begin_upd+=", INDUSTRY_ID="+getIndustry();
                     sqlstr_begin_upd+=", [UPDATE]="+(getUpdate()==true?1:0);
                     sqlstr_begin_upd+=" WHERE [MENAYA_ID]="+menayaid;
                     TRS RS=new TRS(BursaAnalizer_Frame.getConnectToDB(BursaAnalizer_Frame.DBID_DATA).con);
                      RS.execSQL(sqlstr_begin_upd);     
                      
                      tm.setValueAt(getStokSymbol(),sr,2);
                      tm.setValueAt(getStok(),sr,3);
                      //TODO update in view also company ,market,industry and type
                     tm.setValueAt(((MySimleInputByCombo)companyname).getVc1bySelected(),sr,1);
                     tm.setValueAt(((MySimleInputByCombo)marketname).getVc1bySelected(),sr,4);
                    tm.setValueAt(((MySimleInputByCombo)industry).getVc1bySelected(),sr,5);
                     tm.setValueAt(((MySimleInputByCombo)type).getVc1bySelected(),sr,8);
                     tm.setValueAt(getUpdate(),sr,6);
                     aThis.revalidate();
                     aThis.repaint();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        Cancel = new javax.swing.JButton();
        Ok = new javax.swing.JButton();
        marketname = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        symbolname = new javax.swing.JTextField();
        stokname = new javax.swing.JTextField();
        Update = new javax.swing.JCheckBox();
        companyname = new javax.swing.JComboBox();
        type = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        industry = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        DataBaseConnector    base=new Msdb_connect("C:\\SDI_BATool\\data\\base.mdb");
        ((Msdb_connect)base).connect();

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        Ok.setText("OK");
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });

        marketname.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        marketname=new MySimleInputByCombo(null,
            base.con,
            "MARKET_T",
            "MARKET",
            "ID");

        jLabel3.setText("Market");

        jLabel1.setText("Stok");

        jLabel2.setText("Symbol");

        Update.setText("Update");
        Update.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        Update.setMargin(new java.awt.Insets(0, 0, 0, 0));

        companyname.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        companyname=new MySimleInputByCombo(null,
            base.con,
            "COMPANY_T",
            "COMPANY",
            "ID");

        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        type=new MySimleInputByCombo(null,
            base.con,
            "STOCKTYPE_T",
            "STOCKTYPE",
            "ID");

        jLabel4.setText("Company");

        jLabel5.setText("Type");

        jLabel6.setText("Industry");

        industry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        industry=new MySimleInputByCombo(null,
            base.con,
            "INDUSTRY_T",
            "INDUSTRY",
            "ID");
        base.disConnect();

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(Cancel)
                        .add(24, 24, 24)
                        .add(Ok))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(jLabel1))
                        .add(14, 14, 14)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(Update)
                            .add(stokname, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .add(symbolname))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 29, Short.MAX_VALUE)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel6)
                            .add(jLabel5)
                            .add(jLabel4)
                            .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(companyname, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(marketname, 0, 108, Short.MAX_VALUE)
                            .add(type, 0, 108, Short.MAX_VALUE)
                            .add(industry, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 216, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(62, Short.MAX_VALUE)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel3)
                            .add(marketname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(20, 20, 20))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel6)
                            .add(stokname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(industry, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(20, 20, 20)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel2)
                            .add(symbolname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(29, 29, 29)))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(companyname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel4))
                        .add(26, 26, 26)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(type, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel5))
                        .add(23, 23, 23)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(Ok)
                            .add(Cancel)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Update)))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
public boolean accepted=false;    
public static final boolean EDITFLAG=true;
private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
        accepted=true;
        donewupdate();
        this.setVisible(false);
        this.dispose();
}//GEN-LAST:event_OkActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        accepted=false;
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_CancelActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StokRowEditor(true).setVisible(true);
            }
        });
    }

    void setStokSymbol(String snt) {
        symbolname.setText(snt);
    }

    void setStok(String snt) {
        stokname.setText(snt);
    }

    void setCompany(String stn) {
        ((MySimleInputByCombo)companyname).setSelectedbyVc1(stn);
    }

    void setMarket(String stn) {
        ((MySimleInputByCombo)marketname).setSelectedbyVc1(stn);
    }

    void setIndustry(String stn) {
        ((MySimleInputByCombo)industry).setSelectedbyVc1(stn);
    }

    void setType(String stn) {
        ((MySimleInputByCombo)type).setSelectedbyVc1(stn);
    }

    void setUpdate(boolean b) {
        Update.setSelected(b);
    }

    String getStokSymbol() {
        return  symbolname.getText();
    }

    String getStok() {
        return   stokname.getText();
    }

    String getCompany() {
        return    ((MySimleInputByCombo)companyname).getVc2bySelected();
    }

    String getMarket() {
        return     ((MySimleInputByCombo)marketname).getVc2bySelected();
    }

    String getIndustry() {
        return  ((MySimleInputByCombo)industry).getVc2bySelected();
    }

    String getStokType() {

        return      ((MySimleInputByCombo)type).getVc2bySelected();
    }

    boolean getUpdate() {
        return Update.isSelected();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Ok;
    private javax.swing.JCheckBox Update;
    private javax.swing.JComboBox companyname;
    private javax.swing.JComboBox industry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox marketname;
    private javax.swing.JTextField stokname;
    private javax.swing.JTextField symbolname;
    private javax.swing.JComboBox type;
    // End of variables declaration//GEN-END:variables

    private void newstock() {
        throw new UnsupportedOperationException("Not yet implemented");
    }
    
}
