import javax.swing.JFrame;
import org.jdesktop.layout.GroupLayout;
/*
 * StoklistTablePanel.java
 *
 * Created on April 2, 2007, 7:10 PM
 */

/**
 *
 * @author  Dmitry
 */
public class StoklistTablePanel extends javax.swing.JPanel
{
    public StoksListTable slt;
    /** Creates new form StoklistTablePanel */
    public StoklistTablePanel ()
    {
        initComponents ();
        slt=new StoksListTable();
        org.jdesktop.layout.GroupLayout layout=(GroupLayout) this.getLayout ();
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(slt))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(5, 5, 5)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(slt)))
        );
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame tf=new JFrame();
                StoklistTablePanel tr=new StoklistTablePanel();
                tf.add(tr);
                tf.setBounds(tr.getBounds());
                tf.setVisible(true);
            }
        });
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(850, 400));
        setPreferredSize(new java.awt.Dimension(850, 400));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 621, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 419, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
