import javax.swing.ImageIcon;
import javax.swing.JButton;
/*
 * TableControlPanelNB.java
 *
 * Created on March 31, 2007, 8:03 PM
 */

/**
 *
 * @author  Dmitry
 */
public class TableControlPanelNB extends javax.swing.JPanel 
{
    
    TableContrlolPanelNBInterface add=null;
    TableContrlolPanelNBInterface rem=null;
    TableContrlolPanelNBInterface upd=null;
    /** Creates new form TableControlPanelNB */
    
    public TableControlPanelNB ()
    {
        initComponents ();
        
         initSTDButtons(null,false, false, false);
         this.setName("TableControlPanelNB");
    }
    
    public TableControlPanelNB (TableContrlolPanelNBInterface ci)
    {
        initComponents ();
        
         initSTDButtons(ci,true, true, true);
    }
    public TableControlPanelNB(TableContrlolPanelNBInterface ci,boolean tadd, boolean trem, boolean tupd) 
    {
         initComponents ();
         
        initSTDButtons(ci,tadd, trem, tupd);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        Add = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        Update = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true));

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AddActionPerformed(evt);
            }
        });

        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RemoveActionPerformed(evt);
            }
        });

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                UpdateActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(Add)
                .add(21, 21, 21)
                .add(Remove)
                .add(15, 15, 15)
                .add(Update)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Add)
                    .add(Remove)
                    .add(Update))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    public Object ttt=null;
    
    private void AddActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_AddActionPerformed
    {//GEN-HEADEREND:event_AddActionPerformed
        if(add!=null)add.onNewBut();
    }//GEN-LAST:event_AddActionPerformed

    private void RemoveActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_RemoveActionPerformed
    {//GEN-HEADEREND:event_RemoveActionPerformed
        if(rem!=null)rem.onDeleteBut();
    }//GEN-LAST:event_RemoveActionPerformed

    private void UpdateActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_UpdateActionPerformed
    {//GEN-HEADEREND:event_UpdateActionPerformed
        if(upd!=null)upd.onUpdateBut();
    }//GEN-LAST:event_UpdateActionPerformed
    
public void initSTDButtons(TableContrlolPanelNBInterface ci,boolean tadd, boolean trem, boolean tupd) {
        String timgdir = BursaAnalizer_Frame.getImgDir();
        if (tadd) {
            Add.setName (Name.Add);
        Add.setIcon (new ImageIcon(timgdir + "index_add.png"));
        add=ci;
        }

        if (trem) {
            Remove.setName (Name.Remove);
        Remove.setIcon (new ImageIcon(timgdir + "index_delete.png"));
        rem=ci;
        }

        if (tupd) {
            Update.setName (Name.Update);
        Update.setIcon (new ImageIcon(timgdir + "data_replace.png"));
        upd=ci;
        }
    }
    public static final int ADD_BUTTON=1;
    public static final int REMOVE_BUTTON=2;
    public static final int UPDATE_BUTTON=3;
    JButton getControll (int request)
    {
        switch(request)
        {
            case ADD_BUTTON:
                return Add;
            case REMOVE_BUTTON:
                return Remove;
            case UPDATE_BUTTON:
                return Update;
        }
        return null;
    }

static class Name {
        public static final String Add =
            java.util.ResourceBundle.getBundle("LANGen").getString("Add");
        public static final String Remove =
            java.util.ResourceBundle.getBundle("LANGen").getString("Remove");
        public static final String Update =
            java.util.ResourceBundle.getBundle("LANGen").getString("Edit");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    public javax.swing.JButton Remove;
    private javax.swing.JButton Update;
    // End of variables declaration//GEN-END:variables

    
}
