import CDate.CDate;
import DBCONNECT.TRS;
import Utils.LoggerNB;
import Utils.TDoc;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/*
 * TaseDataFactory.java
 *
 * Created on 25 ιεμι 2006, 14:09
 */

/**
 *
 * @author  Student
 */
public class TaseDataFactory extends javax.swing.JFrame {
    
    /** Creates new form TaseDataFactory */
    public TaseDataFactory() {
        initComponents();
        setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        Close = new javax.swing.JButton();
        sp = new javax.swing.JScrollPane();
        TDTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Check = new javax.swing.JButton();
        Download = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        URLTASE = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        dateButtonStart = new CalendarForms.DateButton();
        dateButtonEnd = new CalendarForms.DateButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        Close.setText(java.util.ResourceBundle.getBundle(BursaAnalizer_Frame.getUIInterLan()).getString("Close"));
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        TDTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "File", "Download", "Exist"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        sp.setViewportView(TDTable);

        jLabel1.setText(java.util.ResourceBundle.getBundle(BursaAnalizer_Frame.getUIInterLan()).getString("Available_data_points"));

        Check.setText(java.util.ResourceBundle.getBundle(BursaAnalizer_Frame.getUIInterLan()).getString("Check"));
        Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckActionPerformed(evt);
            }
        });

        Download.setText(java.util.ResourceBundle.getBundle(BursaAnalizer_Frame.getUIInterLan()).getString("Download"));

        jLabel2.setText(java.util.ResourceBundle.getBundle(BursaAnalizer_Frame.getUIInterLan()).getString("Base_Tase_Distribution_URL_:"));

        URLTASE.setText("https://www.tase.co.il/FileDistribution/PackTarget/Full");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setText(java.util.ResourceBundle.getBundle(BursaAnalizer_Frame.getUIInterLan()).getString("begin"));

        jLabel4.setText(java.util.ResourceBundle.getBundle(BursaAnalizer_Frame.getUIInterLan()).getString("end"));

        jLabel5.setText(java.util.ResourceBundle.getBundle(BursaAnalizer_Frame.getUIInterLan()).getString("Select_period_range_to_operate"));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(Check)
                                .add(53, 53, 53)
                                .add(Download))
                            .add(jLabel1)
                            .add(URLTASE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1)))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(145, 145, 145)
                        .add(Close)
                        .add(43, 43, 43))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel3)
                                    .add(jLabel4))
                                .add(30, 30, 30)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(dateButtonStart, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(dateButtonEnd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel5))
                        .addContainerGap())))
            .add(sp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(sp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 197, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(21, 21, 21)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Check)
                    .add(Download))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jLabel5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(URLTASE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3)
                    .add(dateButtonStart, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, Short.MAX_VALUE)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 99, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(22, 22, 22)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel4)
                            .add(dateButtonEnd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(39, 39, 39)
                        .add(Close)))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckActionPerformed
    TableModel dtm=this.TDTable.getModel();
    DefaultTableModel model = (DefaultTableModel)(dtm);
    //model.removeRow(0);
    //https://www.tase.co.il/FileDistribution/PackTarget/Full200607250.zip
    //CDate td=new CDate();
    //model.addRow(new Object[]{td.toString(), URLTASE.getText()+td.toStringTaseFileDate()+".zip",new Boolean(true),"local"});
    this.jTextArea1.setText("");
    buildmissedlist();
    int i,cnt=dtm.getRowCount();
    for (i=0;i<cnt;i++)
    {
    this.jTextArea1.append(dtm.getValueAt(i,0)+"\n");
    
    }
    }//GEN-LAST:event_CheckActionPerformed
    private void buildmissedlist()
    {
     DefaultTableModel model = (DefaultTableModel)(this.TDTable.getModel());
     java.util.List missed = new ArrayList();
     CDate start=new CDate(this.dateButtonStart.getDate());
     CDate end=new CDate(this.dateButtonEnd.getDate());
     java.util.List vset=loadbursavacations();
     end.roll(1);
     TDoc t;
     long diff=end.diff(start);
     while(diff>0)
     {
     t=new TDoc(2);
     t.o[0]=new CDate(start);
     //t.o[1]=new Boolean(false);
     t.o[1]=false;
     //add only work days
     if(start.dayofweek()<6)
     {
         //is it bursa vacation?
        if(inset(vset,start)==false) missed.add(t);
     }
     start.roll(1);
     diff=end.diff(start);
     }
     int i,cnt=missed.size();
     for(i=0;i<cnt;i++)
     {
         t=(TDoc)(missed.get(i));
      model.addRow(new Object[]{t.o[0], URLTASE.getText()+((CDate)(t.o[0])).toStringTaseFileDate()+".zip",true,"local"});
     }
    }
    //load tase vacations from table
    private List loadbursavacations()
    {
     java.util.List set = new ArrayList();
     Connection con=BursaAnalizer_Frame.getConnectToDB(BursaAnalizer_Frame.DBID_BASE).con;
     TRS RS=new TRS(con);
	 try {
	 	  RS.execSQL("SELECT * FROM NOPDAYS");
	 	while(RS.rs.next())
     		{ 
                      try
                        {
                        set.add((new CDate(RS.rs.getDate("Day"))).toString());
                        }catch(Exception e)
                            {
                                	if(LoggerNB.debuging){System.out.println("can't convert date - just skip");}
                                }
                }
         }
                catch (SQLException e) 
            {
            if(LoggerNB.debuging){System.out.println("Error20: " + e);}
        	}
        	finally
        	{
        		RS.close();
     		    RS=null;
        	}
     return set;
    }
    public boolean inset(java.util.List set,CDate element)
    {
     int i,size=set.size();
     for(i=0;i<size;i++)
         if(set.get(i).toString().equals(element.toString())==true)return true;
     return false;
    }
    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
this.dispose();
    }//GEN-LAST:event_CloseActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaseDataFactory().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Check;
    private javax.swing.JButton Close;
    private javax.swing.JButton Download;
    private javax.swing.JTable TDTable;
    private javax.swing.JTextField URLTASE;
    private CalendarForms.DateButton dateButtonEnd;
    private CalendarForms.DateButton dateButtonStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JScrollPane sp;
    // End of variables declaration//GEN-END:variables
    
}
