/*
 * TechnicalAdvAnaSettingsDetector.java
 *
 * Created on 24 ינואר 2009, 23:22
 */



/**
 *
 * @author  Dmitry
 */
public class TechnicalAdvAnaSettingsDetector extends javax.swing.JPanel {

    /** Creates new form TechnicalAdvAnaSettingsDetector */
    public TechnicalAdvAnaSettingsDetector() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RRTest = new javax.swing.JCheckBox();
        RRVal = new javax.swing.JTextField();
        rrrbelt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rrrperiod = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        leaveonlyagreed = new javax.swing.JCheckBox();

        RRTest.setText("Reward Risk");
        RRTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RRTestActionPerformed(evt);
            }
        });

        RRVal.setText("0.33");
        RRVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RRValActionPerformed(evt);
            }
        });

        rrrbelt.setText("5");

        jLabel1.setText("Belt");

        jLabel2.setText("Max RR Ratio");

        jLabel3.setText("%");

        rrrperiod.setMajorTickSpacing(7);
        rrrperiod.setMaximum(77);
        rrrperiod.setMinimum(7);
        rrrperiod.setMinorTickSpacing(1);
        rrrperiod.setPaintLabels(true);
        rrrperiod.setPaintTicks(true);
        rrrperiod.setSnapToTicks(true);
        rrrperiod.setValue(7);

        jLabel4.setText("SR period");

        leaveonlyagreed.setText("Leave only agreed");
        leaveonlyagreed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveonlyagreedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RRTest)
                        .addGap(95, 95, 95)
                        .addComponent(leaveonlyagreed))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RRVal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rrrbelt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addComponent(rrrperiod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RRTest)
                    .addComponent(leaveonlyagreed))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RRVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rrrbelt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rrrperiod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void RRTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RRTestActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_RRTestActionPerformed

private void RRValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RRValActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_RRValActionPerformed

private void leaveonlyagreedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveonlyagreedActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_leaveonlyagreedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox RRTest;
    public javax.swing.JTextField RRVal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JCheckBox leaveonlyagreed;
    public javax.swing.JTextField rrrbelt;
    public javax.swing.JSlider rrrperiod;
    // End of variables declaration//GEN-END:variables

}
