/*
 * TradeDataListTablePanel.java
 *
 * Created on April 2, 2007, 8:38 PM
 */

/**
 *
 * @author  Dmitry
 */
public class TradeDataListTablePanel extends javax.swing.JPanel
{
    
    /** Creates new form TradeDataListTablePanel */
    public TradeDataListTablePanel ()
    {
        initComponents ();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        tdlt = new TradeDataListTable();

        add(tdlt);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public TradeDataListTable tdlt;
    // End of variables declaration//GEN-END:variables
    
}
